## All proprietary files from this list, unless pinned and noted otherwise,
## are from OnePlus Nord CE 2 Lite 5G (CPH2381_11.C.32).
## are from Realme GT Neo 3T  RMX3371_14.0.0.100(EX01).

# Camera
odm/bin/vl53l1_daemon_main
odm/lib/libaiboost.so
odm/lib/libaiboost_hexagon.so
odm/lib/libaiboost_nnlib_sr.so
odm/lib/libaiboost_sr.so
odm/lib/libaiboost_ubwc.so
odm/lib/libDeVIS.so
odm/lib/libosie_process.so
odm/lib/libosie_stub.so
odm/lib64/libFDClite.so
odm/lib64/libFaceBeautyPICap.so
odm/lib64/libFaceWhiten.so
odm/lib64/libHdrVideo.so
odm/lib64/libImageWarpMask.so
odm/lib64/libNightVideo.so
odm/lib64/libQnnHtpAltPrepStub.so
odm/lib64/libQnnHtpStub.so
odm/lib64/libSEC.HybridHDR.so
odm/lib64/libStarMode.so
odm/lib64/libSuperRaw.so
odm/lib64/libaiboost.so
odm/lib64/libaiboost_hexagon.so
odm/lib64/libaiboost_nnlib_sr.so
odm/lib64/libaiboost_sr.so
odm/lib64/libaiboost_ubwc.so
odm/lib64/libaisal.so
odm/lib64/libancbase_rt_fusion.so
odm/lib64/libancbase_rt_retain.so
odm/lib64/libarcsoft_hdr_couple_api_v4.so
odm/lib64/libarcsoft_hdr_denoise_api_v4.so
odm/lib64/libarcsoft_high_dynamic_range_couple_v4.so
odm/lib64/libarcsoft_high_dynamic_range_v4.so
odm/lib64/libarcsoft_hta.so
odm/lib64/libarcsoft_pic_best.so
odm/lib64/libarcsoft_smart_denoise_v4.so
odm/lib64/libarcsoft_super_night_se_raw.so
odm/lib64/libarcsoft_videoautozoom.so
odm/lib64/libcalculator_domains.so
odm/lib64/libcom.oplus.calidatacontainer.so
odm/lib64/libcvface_api.so
odm/lib64/libdmtp.so
odm/lib64/libfastov_dsp.so
odm/lib64/libhci_face_camera_api.so
odm/lib64/libosie_process.so
odm/lib64/libosie_stub.so
odm/lib64/libshdr_stub.so
odm/lib64/libsnpe_htp.so
odm/lib64/libvl53l1_daemon.so
odm/lib64/sensors.hal.tof.so
odm/lib64/vendor.oplus.hardware.cameraextension-V1-service-impl.so
odm/lib64/vendor.oplus.hardware.cammidasservice-V1-ndk_platform.so
vendor/lib/libextcamera_client.so
vendor/lib/vendor.oplus.hardware.extcamera@1.0.so
vendor/lib64/camera/com.qti.eeprom.truly_cmb433.so
vendor/lib64/com.qti.feature2.gs.so
vendor/lib64/libFace3DTA.so
vendor/lib64/libFace3D_hlos.so
vendor/lib64/libQ6MSFR_manager_stub.so
vendor/lib64/libcamxncs.so
vendor/lib64/libcvp2.so
vendor/lib64/libcvp2_hfi.so
vendor/lib64/libextcamera_client.so
vendor/lib64/libface3d_dev.so
vendor/lib64/libgui1_vendor.so
vendor/lib64/libmidasserviceintf_aidl.so
vendor/lib64/libopenvx.so
vendor/lib64/vendor.oplus.hardware.cameraextension-V1-ndk_platform.so
vendor/lib64/vendor.oplus.hardware.cammidasservice-V1-ndk_platform.so
vendor/lib64/vendor.oplus.hardware.commondcs-V1-ndk_platform.so
vendor/lib64/vendor.oplus.hardware.extcamera@1.0.so
vendor/lib64/vendor.qti.hardware.camera.postproc@1.0-service-impl.so|c47e94efa891cf09dd4f20ea0d271ac615f0ee8d

# Camera (All)
odm/lib/libc++_shared.so
odm/lib64/lib2DSlender.so
odm/lib64/libAlgoInterface.so
odm/lib64/libAlgoProcess.so
odm/lib64/libAncFilter.so
odm/lib64/libAncHumBokeh.so
odm/lib64/libAncHumBokehPost.so
odm/lib64/libAncHumVideoBase.so
odm/lib64/libAncHumanDoubleExposure.so
odm/lib64/libAncHumanRetain.so
odm/lib64/libAncHumanSegFigureFusion.so
odm/lib64/libAncSegBaseSdk.so
odm/lib64/libAncSegmentSdk.so
odm/lib64/libBokehPre.so
odm/lib64/libCOppLceTonemapAPI.so
odm/lib64/libCaptureBokeh.so
odm/lib64/libDeVIS.so
odm/lib64/libEIS.so
odm/lib64/libFaceBeautyCap.so
odm/lib64/libFaceBeautyJni.so
odm/lib64/libFaceBeautyPre.so
odm/lib64/libFaceDistortionCorrection.so
odm/lib64/libFilterWrapper.so
odm/lib64/libOGLManager.so
odm/lib64/libOPLUS_SCPortrait.so
odm/lib64/libPerfectColor.so
odm/lib64/libPerfectlyClearCrux.so
odm/lib64/libPerfectlyClearCruxOpt.so
odm/lib64/libPlatformValidatorShared.so
odm/lib64/libPolarrRender.so
odm/lib64/libPreviewDecisionOld.so
odm/lib64/libRedeyeReduce.so
odm/lib64/libSNPE.so
odm/lib64/libSNPE_G.so
odm/lib64/libSonyIMX471RmscLibrary.so
odm/lib64/libSuperTextWrapper.so
odm/lib64/libTrafficMode.so
odm/lib64/libVDBayerHDR.so
odm/lib64/libVDBlurless.so
odm/lib64/libVDDualCameraBlurlessAPI.so
odm/lib64/libVDExternal.so
odm/lib64/libVDPostureDetection.so
odm/lib64/libVDSuperPhotoAPI.so
odm/lib64/libVDUpScale.so
odm/lib64/libVideoEnhance.so
odm/lib64/libWaterMark.so
odm/lib64/libWaterMode.so
odm/lib64/libXDocProcessSDK.so
odm/lib64/libYTCommon.so
odm/lib64/lib_rectify.so
odm/lib64/libaisd.so
odm/lib64/libaiseg.so
odm/lib64/libalCFR.so
odm/lib64/libancbase_rt_bokeh.so
odm/lib64/libancbase_segbase.so
odm/lib64/libancbase_segment.so
odm/lib64/libaps_frame_registration.so
odm/lib64/libapsdarksight.so
odm/lib64/libapsexif.so
odm/lib64/libapsjpeg.so
odm/lib64/libapspng.so
odm/lib64/libarcsoft_aicolor_image.so
odm/lib64/libarcsoft_aicolor_video.so
odm/lib64/libarcsoft_distortion_correction.so
odm/lib64/libarcsoft_dualcam_bokeh_api.so
odm/lib64/libarcsoft_dualcam_refocus_left.so
odm/lib64/libarcsoft_dualcam_refocus_preview.so
odm/lib64/libarcsoft_dualcam_refocus_uw.so
odm/lib64/libarcsoft_hdr_couple_api.so
odm/lib64/libarcsoft_hdr_denoise_api.so
odm/lib64/libarcsoft_hdrplus_hvx_stub.so
odm/lib64/libarcsoft_high_dynamic_range.so
odm/lib64/libarcsoft_high_dynamic_range_couple.so
odm/lib64/libarcsoft_lensstaindetection.so
odm/lib64/libarcsoft_low_light_hdr.so
odm/lib64/libarcsoft_low_light_hdr_for_neon.so
odm/lib64/libarcsoft_portraitSN_hvx_stub.so
odm/lib64/libarcsoft_portrait_super_night_raw.so
odm/lib64/libarcsoft_preview_antibanding.so
odm/lib64/libarcsoft_scbokeh_image.so
odm/lib64/libarcsoft_scbokeh_video.so
odm/lib64/libarcsoft_smart_denoise.so
odm/lib64/libarcsoft_super_night_raw.so
odm/lib64/libbsproxy.so
odm/lib64/libc++_shared.so
odm/lib64/libcalculator.so
odm/lib64/libcalculator_htp.so
odm/lib64/libcdm_metrics_protos.so
odm/lib64/libcdm_protos.so
odm/lib64/libdav1d.so.4
odm/lib64/libeffect_custom.so
odm/lib64/libhwconfigurationutil.so
odm/lib64/libhyperlapse.so
odm/lib64/libimgClarityEvaluate.so
odm/lib64/libml_util.so
odm/lib64/libmotionblur.so
odm/lib64/libmpbase.so
odm/lib64/libop-ai-beauty-body-detection.so
odm/lib64/libop-ai-beauty-faceretouch-cn.so
odm/lib64/libormshalclient.so
odm/lib64/libpngwrapper.so
odm/lib64/libsnpe_dsp_domains_v2.so
odm/lib64/libsnpe_dsp_domains_v3.so
odm/lib64/libsnpe_loader.so
odm/lib64/libsnpeml.so
odm/lib64/libstblur_api.so
odm/lib64/libstblur_capture_api.so
odm/lib64/libstdc++.so
odm/lib64/libstface_fd_api.so
odm/lib64/libstfd_mobile_api.so
odm/lib64/libsymphony-cpu.so
odm/lib64/libsymphonypower.so
odm/lib64/libwatermark_photo.so
odm/lib64/vendor.oplus.hardware.orms@1.0.so
vendor/lib64/hw/camera.qcom.so
vendor/lib64/hw/com.qti.chi.override.so
vendor/lib64/com.qti.feature2.frameselect.so
vendor/lib64/com.qti.feature2.fusion.so
vendor/lib64/com.qti.feature2.generic.so
vendor/lib64/com.qti.feature2.hdr.so
vendor/lib64/com.qti.feature2.memcpy.so
vendor/lib64/com.qti.feature2.mfsr.so
vendor/lib64/com.qti.feature2.qcfa.so
vendor/lib64/com.qti.feature2.rawhdr.so
vendor/lib64/com.qti.feature2.rt.so
vendor/lib64/com.qti.feature2.serializer.so
vendor/lib64/com.qti.feature2.stub.so
vendor/lib64/com.qti.feature2.swmf.so
vendor/lib64/libC2D2.so
vendor/lib64/libCB.so
vendor/lib64/libbitmlengine.so
vendor/lib64/libcamera_nn_stub.so
vendor/lib64/libcamerapostproc.so
vendor/lib64/libcamxfacialfeatures.so
vendor/lib64/libcamxfdalgo.so
vendor/lib64/libcamxfdengine.so
vendor/lib64/libcamxifestriping.so
vendor/lib64/libcamximageformatutils.so
vendor/lib64/libcamxstatscore.so
vendor/lib64/libcamxswispiqmodule.so
vendor/lib64/libcamxswprocessalgo.so
vendor/lib64/libcamxtintlessalgo.so
vendor/lib64/libchilog.so
vendor/lib64/libcom.qti.chinodeutils.so
vendor/lib64/libcvp_common.so
vendor/lib64/libcvpcpuRev_skel.so
vendor/lib64/libmidasserviceintf.so
vendor/lib64/libmmcamera_faceproc.so
vendor/lib64/libmmcamera_faceproc2.so
vendor/lib64/libnanopb.so
vendor/lib64/libofflinelog.so
vendor/lib64/libos.so
vendor/lib64/libskewknob.so
vendor/lib64/libswregistrationalgo.so
vendor/lib64/libsynx.so
vendor/lib64/libthreadutils.so
vendor/lib64/vendor.oplus.hardware.cammidasservice@1.0.so
